export const PERFILES = {
  EMPRENDEDOR_SATURADO: {
    tag: "El Emprendedor Saturado",
    ref: "TRABAJÁS MUCHO. PERO VÁS EN CÍRCULOS.",
    desc: "Tu problema no es el tiempo. Es el foco. Estás tan adentro del ruido que no podés ver el mapa. Vivís apagando incendios, sentís que si no empujás, nada avanza.",
    verdad: "No estás saturado por trabajar mucho. Estás saturado porque el negocio depende de que vos estés en todo.",
    cierreTitulo: "EL CAOS NO SE AGUANTA. SE ORDENA.",
    cierreTxt: "¿Te describe? Juntémonos y hacemos un mapa completo para que salgas andando. Sin teoría, sin vueltas, al hueso. ¿Estás listo?",
    cta: "DALE →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Emprendedor Saturado. Me gustaría ordenarme.",
    saludo: "[nombre], lo que sentís tiene nombre. Y no es falta de esfuerzo.",
  },
  LIDER_SOLA: {
    tag: "La Líder que Lidera Solo/a",
    ref: "SOSTENÉS TODO. Y NADIE TE SOSTIENE A VOS.",
    desc: "Tenés gente. Tenés estructura. Pero cuando hay que decidir, resolver, empujar — todo termina en vos. No porque seas desconfiado. Sino porque el sistema no está diseñado para funcionar sin vos. Y eso agota.",
    verdad: "No es que tu equipo no sirve. Es que nunca les enseñaste a trabajar sin que estés.",
    cierreTitulo: "LIDERÁS BIEN. PERO ESO SOLO NO TE ALCANZA.",
    cierreTxt: "Hay algo muy concreto que podemos hacer. No es magia, no es teoría. Es ordenar el sistema para que el negocio funcione aunque vos no estés mirando. ¿Arrancamos?",
    cta: "SÍ, ARRANCAMOS →",
    waMsg: "Hola Sindy, hice el diagnóstico y soy La Líder que Lidera Solo/a. Necesito que alguien me sostenga a mí también.",
    saludo: "[nombre], lo que cargás tiene nombre. Y tiene solución.",
  },
  PROFESIONAL_INVISIBLE: {
    tag: "El Profesional Invisible",
    ref: "SABEMOS QUE SABÉS LO QUE VALÉS. PERO PARECE QUE NADIE LO VE.",
    desc: "Tenés talento real. Pero no lográs traducirlo en un mensaje que te diferencie. Competís por precio sin quererlo, hasta cobrás menos de lo que deberías y te sentís infravalorado.",
    verdad: "No sos uno más. Pero estás comunicando como si lo fueras.",
    cierreTitulo: "TU VALOR EXISTE. FALTA EL MENSAJE.",
    cierreTxt: "¿Te hicimos pensar? Entonces hay algo concreto para hacer. Juntémonos para ver tu posicionamiento real.",
    cta: "SÍ, POR FAVOR →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Profesional Invisible. Quiero trabajar mi posicionamiento.",
    saludo: "[nombre], tu valor es real. El problema es que nadie lo está viendo.",
  },
  EQUIPO_DESALINEADO: {
    tag: "El Equipo Desalineado",
    ref: "TRABAJAN, TRABAJAN. PERO NO AVANZAN.",
    desc: "Hay energía, hay compromiso. Pero cada uno interpreta a su manera. El resultado: reuniones que no definen nada, tareas duplicadas, y un desgaste silencioso que se acumula.",
    verdad: "No están desmotivados. Están desorientados. Y eso tiene dueño.",
    cierreTitulo: "MALA NOTICIA: EL DESORDEN NO ES DEL EQUIPO. ES DE LA DIRECCIÓN.",
    cierreTxt: "Si tu equipo está así, hay algo que tenés que hacer esta semana. Una conversación para encontrar el sentido.",
    cta: "QUIERO QUE TIREMOS PARA EL MISMO LADO →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y tengo un Equipo Desalineado. Quiero alinearlo.",
    saludo: "[nombre], el problema no es tu equipo. Es que nadie les explicó para dónde van.",
  },
  ESCEPTICO: {
    tag: "El Empresario Escéptico",
    ref: "TENÉS GENTE. TENÉS ESTRUCTURA. Y ALGO NO CIERRA.",
    desc: "Pagás por cosas que no estás seguro de que sirvan. Tu entorno opina, pero parece que nunca le pega en el blanco. Sospechás que estás mal informado.",
    verdad: "No necesitás más información. Necesitás que alguien te diga la verdad sin maquillaje.",
    cierreTitulo: "LA SOSPECHA TIENE NOMBRE.",
    cierreTxt: "Si te incomoda, pasa algo. Hablemos francamente. De lo que está pasando, de lo que no te cierra.",
    cta: "QUIERO LA VERDAD →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Empresario Escéptico. Quiero una conversación honesta.",
    saludo: "[nombre], tu instinto de que algo no cierra — es correcto.",
  },
  NUEVA_GENERACION: {
    tag: "La Nueva Generación",
    ref: "HACÉS UN MONTÓN. NADIE LO VE. NADIE LO DICE.",
    desc: "Tenés capacidad real, valores claros y compromiso genuino. Pero estás en una estructura que no te escucha, no te toma en serio o no te da espacio para crecer.",
    verdad: "No te falta capacidad. Te falta un marco donde tu capacidad valga lo que vale.",
    cierreTitulo: "NO PEDÍS MUCHO. PEDÍS LO JUSTO.",
    cierreTxt: "¿Te suena? Conversemos y vemos cómo te damos una mano.",
    cta: "SÍ, DALE →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy La Nueva Generación. Quiero encontrar mi lugar.",
    saludo: "[nombre], lo que aportás es real. El problema es que el sistema donde estás no está diseñado para verlo.",
  },
  VENDEDOR_SIN_RESULTADOS: {
    tag: "El Vendedor sin Resultados",
    ref: "PONÉS EL CUERPO. PONÉS EL ALMA. Y LA CAJA NO LO REFLEJA.",
    desc: "Vendés, te movés, intentás, probás. Pero cuando mirás la caja no ves los resultados que esperabas. Vivís en un péndulo: un día convencido, al otro listo para tirar todo.",
    verdad: "No te falta ganas. Te falta una estrategia que convierta lo que hacés en resultados concretos.",
    cierreTitulo: "EL ESFUERZO SIN DIRECCIÓN ES DESGASTE.",
    cierreTxt: "Hay algo concreto para ordenar. No es magia, es claridad comercial. ¿Arrancamos?",
    cta: "SÍ, ARRANCAMOS →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Vendedor sin Resultados. Necesito claridad comercial.",
    saludo: "[nombre], el esfuerzo está. Lo que falta es que ese esfuerzo vaya en la dirección correcta.",
  },
  ORDEN_PARA_CRECER: {
    tag: "El que Necesita Orden para Crecer",
    ref: "CRECISTE RÁPIDO. Y SABÉS QUE ASÍ NO PODÉS SEGUIR.",
    desc: "Te fue bien. Creciste rápido. Tenés ingresos, movimiento, demanda. Pero también tenés caos, falta de procesos y la sensación de que si seguís así vas a desbarrancar.",
    verdad: "No necesitás cambiar lo que funciona. Necesitás construir el sistema que sostenga lo que ya lograste.",
    cierreTitulo: "CRECER SIN ESTRUCTURA ES CAER CON IMPULSO.",
    cierreTxt: "No viene a complicarte la vida. Viene a ordenar lo que ya lograste para que no se rompa cuando más lo necesitás.",
    cta: "QUIERO ORDENARME →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y necesito Orden para Crecer. Quiero estructurar mi negocio.",
    saludo: "[nombre], creciste. Ahora el desafío es no desbarrancar con el propio impulso.",
  },
} as const

export type PerfilKey = keyof typeof PERFILES
