export const PERFILES = {
  SATURADO: {
    tag: "Saturado",
    ref: "TRABAJÁS MUCHO. PERO VÁS EN CÍRCULOS.",
    desc: "Tu problema no es el tiempo. Es el foco. Estás tan adentro del ruido que no podés ver el mapa. Vivís apagando incendios, sentís que si no empujás, nada avanza.",
    verdad: "No sabés dónde está el cuello de botella. Y eso es exactamente lo que te tiene corriendo en círculos.",
    cierreTitulo: "EL CAOS NO SE AGUANTA. SE ORDENA.",
    cierreTxt: "¿Te describe? Juntémonos y hacemos un mapa completo para que salgas andando. Sin teoría, sin vueltas, al hueso. ¿Estás listo?",
    cta: "DALE →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy Saturado. Me gustaría ordenarme.",
    saludo: "[nombre], lo que sentís tiene nombre. Y no es falta de esfuerzo.",
  },
  LIDER_QUE_NECESITA_APOYO: {
    tag: "El Líder sin Herramientas",
    ref: "TODO PASA POR VOS. Y NO ES PORQUE QUIERAS.",
    desc: "Tenés equipo, tenés estructura. Pero cada decisión, cada problema, cada 'che, esto cómo lo resuelvo' — termina en vos. No es que no confiés. Es que nadie te dio las herramientas para que funcione distinto.",
    verdad: "No te falta carácter. Te falta un sistema y el criterio para usarlo. Eso no se aprende solo, mirando.",
    cierreTitulo: "NO PODÉS SEGUIR SOSTENIENDO TODO SOLO.",
    cierreTxt: "Esto se resuelve con herramientas concretas, no con más esfuerzo de tu parte. Armamos el sistema para que el negocio funcione aunque no estés mirando cada cosa. ¿Arrancamos?",
    cta: "QUIERO LAS HERRAMIENTAS →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Líder sin Herramientas. Necesito un sistema para no sostener todo yo.",
    saludo: "[nombre], lo que cargás tiene nombre. Y se resuelve con herramientas, no con más esfuerzo.",
  },
  INDEPENDIENTE_EN_CRECIMIENTO: {
    tag: "El que Vale Más de lo que Cobra",
    ref: "TU TRABAJO VALE. TU FACTURACIÓN NO LO REFLEJA.",
    desc: "Hacés las cosas bien. Tenés criterio, experiencia, resultados. Pero a la hora de cobrar lo que valés, o de posicionarte como corresponde, algo te frena. Competís por precio sin querer, o esperás que el mercado te reconozca solo.",
    verdad: "No te falta nivel. Te falta el posicionamiento y la estrategia para que ese nivel se traduzca en lo que cobrás.",
    cierreTitulo: "TU VALOR EXISTE. FALTA LA ESTRATEGIA PARA COBRARLO.",
    cierreTxt: "Esto se ordena con posicionamiento real, no con más trabajo. Vemos cómo te posicionás y cómo eso se traduce en resultados concretos. ¿Lo vemos?",
    cta: "SÍ, QUIERO VERLO →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El que Vale Más de lo que Cobra. Quiero trabajar mi posicionamiento.",
    saludo: "[nombre], tu nivel es real. Lo que falta es la estrategia para que se vea — y se cobre.",
  },
  EQUIPO_DESALINEADO: {
    tag: "El Equipo Desalineado",
    ref: "TRABAJAN, TRABAJAN. PERO NO AVANZAN.",
    desc: "Hay energía, hay compromiso. Pero cada uno interpreta a su manera. El resultado: reuniones que no definen nada, tareas duplicadas, y un desgaste silencioso que se acumula.",
    verdad: "El problema no es tu equipo. Es que les decís qué hacer pero no les das instrucciones claras, objetivos claros ni límites claros. Cada uno resuelve como puede.",
    cierreTitulo: "MALA NOTICIA: EL DESORDEN NO ES DEL EQUIPO. ES DE LA DIRECCIÓN.",
    cierreTxt: "Si tu equipo está así, hay algo que tenés que hacer esta semana. Una conversación para encontrar el sentido.",
    cta: "QUIERO QUE TIREMOS PARA EL MISMO LADO →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y tengo un Equipo Desalineado. Quiero alinearlo.",
    saludo: "[nombre], el problema no es tu equipo. Es que nadie les explicó para dónde van.",
  },
  ESCEPTICO: {
    tag: "El Empresario Escéptico",
    ref: "TENÉS GENTE. TENÉS ESTRUCTURA. Y ALGO NO CIERRA.",
    desc: "Pagás por cosas que no estás seguro de que sirvan. Tu entorno opina, pero parece que nunca le pega en el blanco. Sospechás que estás mal informado.",
    verdad: "En el fondo, pedir ayuda te parece admitir debilidad. Entonces buscás que otro tome las decisiones difíciles — y si salen mal, no es tu culpa.",
    cierreTitulo: "LA SOSPECHA TIENE NOMBRE.",
    cierreTxt: "Si te incomoda, pasa algo. Hablemos francamente. De lo que está pasando, de lo que no te cierra.",
    cta: "QUIERO LA VERDAD →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Empresario Escéptico. Quiero una conversación honesta.",
    saludo: "[nombre], tu instinto de que algo no cierra — es correcto.",
  },
  NUEVA_GENERACION: {
    tag: "El que Tiene la Responsabilidad sin la Autoridad",
    ref: "RESPONDÉS POR TODO. PERO TODAVÍA NO TE TERMINAN DE ESCUCHAR.",
    desc: "Tenés el cargo, la responsabilidad, las horas puestas. Pero las decisiones importantes siguen pasando por otro lado, o tenés que convencer cada vez que tu criterio vale. Estás en el medio: ni te dejan soltar del todo, ni te dan el lugar completo.",
    verdad: "No te falta preparación. Te falta que tu rol tenga el peso que tu trabajo ya tiene. Y eso no se gana solo con tiempo — se construye con estrategia.",
    cierreTitulo: "NO PEDÍS MÁS DE LO QUE TE CORRESPONDE.",
    cierreTxt: "Esto se trabaja con estrategia de posicionamiento interno — cómo hacer que tu rol pese lo que tu trabajo ya pesa. ¿Lo ordenamos?",
    cta: "SÍ, ORDENEMOSLO →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y siento que tengo la responsabilidad pero no la autoridad. Quiero trabajar esto.",
    saludo: "[nombre], tu trabajo ya pesa. Ahora falta que tu rol pese igual.",
  },
  AREA_COMERCIAL_SIN_RESULTADOS: {
    tag: "El Área Comercial sin Resultados",
    ref: "PONÉS EL CUERPO. PONÉS EL ALMA. Y LA CAJA NO LO REFLEJA.",
    desc: "Vendés, te movés, intentás, probás. Pero cuando mirás la caja no ves los resultados que esperabas. Vivís en un péndulo: un día convencido, al otro listo para tirar todo.",
    verdad: "No tenés método ni procesos. Te faltan datos para tomar mejores decisiones — pero ni sabés cuáles ni cómo obtenerlos.",
    cierreTitulo: "EL ESFUERZO SIN DIRECCIÓN ES DESGASTE.",
    cierreTxt: "Hay algo concreto para ordenar. No es magia, es claridad comercial. ¿Arrancamos?",
    cta: "SÍ, ARRANCAMOS →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y soy El Área Comercial sin Resultados. Necesito claridad comercial.",
    saludo: "[nombre], el esfuerzo está. Lo que falta es que ese esfuerzo vaya en la dirección correcta.",
  },
  SIN_PROFESIONALIZAR_LA_EMPRESA: {
    tag: "La Empresa que Necesita Profesionalizarse",
    ref: "TENÉS TODO PARA DAR EL SALTO. Y AÚN NO LO DISTE.",
    desc: "La empresa funciona, factura, tiene años. Pero sigue operando con la lógica de cuando era más chica: procesos a medio hacer, roles que no están del todo definidos, decisiones que dependen de memoria y costumbre, no de sistema.",
    verdad: "No es que esté mal lo que construiste. Está bien. El problema es que ya es momento de profesionalizarlo, y seguís postergándolo.",
    cierreTitulo: "LO QUE FUNCIONÓ HASTA ACÁ, NO ES SUFICIENTE PARA LO QUE SIGUE.",
    cierreTxt: "Profesionalizar no es complicar todo. Es poner sistema donde hoy hay costumbre. Armamos el plan para dar ese salto sin frenar lo que ya funciona. ¿Arrancamos?",
    cta: "QUIERO PROFESIONALIZAR →",
    waMsg: "Hola, hice el diagnóstico en diagnostico.mejoraok.com y necesito profesionalizar mi empresa. Quiero ver el plan.",
    saludo: "[nombre], lo que construiste está bien. Ahora toca el siguiente nivel: profesionalizarlo.",
  },
} as const

export type PerfilKey = keyof typeof PERFILES
